// Generated by ts-toolkit, to update run `yarn tsk install`
// Inspired by https://github.com/iamturns/create-exposed-app/blob/master/.huskyrc.js
module.exports = {
  hooks: {
    "pre-commit": "yarn lint-staged",
  },
};
