// Generated by ts-toolkit, to update run `yarn tsk install`
// Inspired by https://github.com/iamturns/create-exposed-app/blob/master/importsort.config.js
module.exports = {
  ".js": {
    parser: "babylon",
    style: "module",
  },
  ".ts": {
    parser: "typescript",
    style: "module",
  },
};
